Remove blockchain iterator
input-output-hk/cardano-byron-cli pull request #81
Opened 2018-12-05 11:12 UTC by edolstra

This removes the blockchain iterator, instead using the one in rust-cardano. (I've merged @mzabaluev's recent changes to the former into the latter.) 

Also some misc. fixes to use the improved `block_read` et al. from storage instead of the local clone of that function.

2018-12-05 15:20 UTC, NicolasDP approved these changes

2018-12-18 13:55 UTC, NicolasDP requested changes
I found a problem when trying to run these changes locally:

```thread 'main' panicked at 'Block [127, 20, 30, 162, 110, 24, 156, 156, 176, 158, 36, 115, 246, 73, 149, 97, 1, 29, 93, 60, 144, 221, 100, 47, 222, 133, 156, 224, 34, 130, 163, 174] not found', src\blockchain\peer.rs:293:25```

This happens when we try to load the tip before syncing the blockchain.

I tried this PR, with:

```
cargo run -- blockchain new testnet --template=testnet
cargo run -- blockchain pull testnet
```

2018-12-19 12:55 UTC, mzabaluev reviewed
The changes look good. Please investigate and fix the crash, though.

2018-12-21 15:10 UTC, edolstra commented
The crash should be fixed by 8c5bbba722b8621b7ff0c781edd2c3e6a20da67f. I also updated the PR to use rust-cardano master.

2018-12-21 15:51 UTC, NicolasDP approved these changes

2018-12-21 17:08 UTC, merged